### ISSUE TITLE
Errands v2

### ISSUE THREAD

**Issue by JCL38-ORANGE** [cloudfoundry/bosh-notes#33]
Hello,

I would like to know if the feature errand v2 (https://github.com/cloudfoundry/bosh-notes/blob/master/errands-v2.md) is fully available.
I have install BOSH 263.1.0 as a pre-requisite. It is OK with the manifest file.
But when I launch the command "bosh -d myDeployment errands", my errand doesn't appear in stdout.
It is not possible to trigger it. Maybe the 
Thanks in advance and regards,

**Comment by cppforlife** [comment]
errands v2 is complete: http://bosh.io/docs/errands#include-in-deployment. please reach out to us over slack on github.com/cloudfoundry/bosh issues with more details if it does not work in your env.
