### ISSUE TITLE
Using "partial templates" inside bosh templates in releases

### ISSUE THREAD

**Issue by allomov** [cloudfoundry/bosh-notes#6]
I think that templates for jobs would be easier to create if bosh-template library had something like "partial templates" helpers.

For instance you can look at [director.yml.erb.erb](https://github.com/cloudfoundry/bosh/blob/master/release/jobs/director/templates/director.yml.erb.erb). It has [a large block](https://github.com/cloudfoundry/bosh/blob/master/release/jobs/director/templates/director.yml.erb.erb#L201-L390) for each IaaS it supports. If we could use partials, we are able to extract this IaaS specific settings to distinct templates. The resulting code will be much cleaner, something like this:

``` erb
<% if_p('aws') do %>
  <%= render 'cpi/aws' %>
<% end %>
<% if_p('openstack') do %>
  <%= render 'cpi/openstack' %>
<% end %>
...
```

What do you think?

**Comment by cppforlife** [comment]
I think this will mask the actual problem -- why is the template file so complicated? Specifically talking about the director.yml.erb: since we are pulling out CPIs from the bosh release that file will significantly shrink and splitting it up will not be necessary.

Do you have other concrete examples where you think render will be helpful?

**Comment by allomov** [comment]
Agree with you.

But sometimes this functionality is preferable for a config with large amount of options. For instance, in 
[logsearch/logsearch-boshrelease](https://github.com/logsearch/logsearch-boshrelease/blob/develop/jobs/parser/templates/bin/parser_ctl#L52-L54) you can see how in `_ctl` file, that is aimed to run service, a large config file is concatenated from smaller pieces. This smaller pieces are easier to maintain, but `_ctl` script doesn't seem to be the right place to render it.

**Comment by dpb587-pivotal** [comment]
Closing due to age - feel free to follow up if this continues to be a significant issue and you would like to continue discussion.
