### ISSUE TITLE
When doing AZ work don't forget about vSphere and those who cannot collapse AZs to a single job

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/bosh-notes#7]
https://github.com/cloudfoundry/bosh-notes/blob/master/availability-zones.md

In our deployment we have a vSphere datacenter to separate AZs.  So, this is a reminder that if you fix AZ support for AWS and not for our use case do what you can to help ensure cf-release continues to provide a way to uniquely identify a job/index.

Currently the CC for example has template like this:
https://github.com/cloudfoundry/cloud_controller_ng/blob/5257a8af6990e71cd1e34ae8978dfe4773b32826/bosh-templates/cloud_controller_worker_ctl.erb#L48

If AWS AZ is fixed I would be afraid that runtime developers would begin assuming that a CF job will be uniquely identifiable via index only:

```
exec chpst -u vcap:vcap bundle exec rake <%= task_name %>[cc_global_worker.<%= spec.index %>.$INDEX]
```

Config like that will break those of us that still have to spread CF installations across several deployments.

**Comment by cppforlife** [comment]
One of the potential changes in AZ proposal is to replace index with a UUID e.g `cc/e464...`. What do you think about that?

**Comment by youngm** [comment]
@cppforlife That would work with the main problem I'm worried about here.

Some side thoughts to consider.  We use the job and index to identify and instance for things like monitoring so for us the UUID would need to at least be stable for the life of the deployment.

We occasionally have run into situations where we've needed to delete a deployment and re-create it so it would be nice if the index could persist beyond the life of a deployment but this isn't a strong requirement for us.

Also, Loggregator today uses the index in log messages.  Though this is the source of another outstanding and semi related issue [0].  Perhaps loggregator UI could just display a short UUID and short form of app instance uuid for app logs?  Anyway something else to consider.

[0] https://groups.google.com/a/cloudfoundry.org/d/msg/vcap-dev/L2RSXfX_nfY/Lk3dOq_b6HMJ

**Comment by cppforlife** [comment]
Related to https://github.com/cloudfoundry/bosh-notes/issues/1

**Comment by cppforlife** [comment]
going to close this one since this feature was shipped some time ago. if we've missed something feel free to reopen.
