### ISSUE TITLE
Director UAA integration

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry/bosh-notes#8]
Initial proposal: https://github.com/cloudfoundry/bosh-notes/blob/master/uaa.md

**Comment by rkoster** [comment]
Using director UUID's in scopes seems like a really clean way of handeling scopes. The `bosh.director.admin` scope looks useful as well could for example be used by service broker operators.
What would also be nice is a global read only scope for service helpdesk/support.

**Comment by cppforlife** [comment]
Closing as first-pass UAA integration is complete.
